---
- name: check apt last update
  stat: path=/var/cache/apt
  register: apt_cache_stat
  tags: common

- name: update apt if needed
  apt: update_cache=yes
  when: apt_cache_stat is defined and ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12

- name: Update language
  sudo: yes
  apt: pkg=language-pack-en state=present
  tags: common
