---
- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*db$' line="192.168.111.223 db" state=present
  tags: etc/hosts

- name: Install libpng-dev
  apt: pkg=libpng-dev state=installed
  sudo: yes
  tags: libpng-dev

- name: Install libfontconfig-dev
  apt: pkg=libfontconfig-dev state=installed
  sudo: yes
  tags: libfontconfig-dev

- name: Register linuxbrew path
  stat: path=/home/vagrant/.linuxbrew
  register: linuxbrew_path

- name: Install linuxbrew
  include: linuxbrew.yml
  when: linuxbrew_path.stat.exists == false

- name: Create global .gitconfig with default user.name and user.email.
  sudo: no
  template: src=.gitconfig.j2 dest=/home/vagrant/.gitconfig force=no
  tags: git

- name: Install nodejs, npm, and npm packages
  include: node.yml
  tags: nodejs

- name: Install heroku-toolbelt
  sudo: no
  shell: /home/vagrant/.linuxbrew/bin/brew install heroku-toolbelt
  tags: heroku-toolbelt

- name: Start in /vagrant directory when ssh
  lineinfile: dest=/home/vagrant/.bashrc regexp='^cd /vagrant/project$' line="cd /vagrant/project" state=present
  tags: .bashrc
